// Date: 3/5/2017 4:56:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.TTM.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelKetchup extends ModelBase
{
  //fields
    ModelRenderer KBase;
    ModelRenderer KNossel;
    ModelRenderer KPart;
  
  public ModelKetchup()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      KBase = new ModelRenderer(this, 0, 0);
      KBase.addBox(-2.5F, 15F, -1.5F, 5, 9, 3);
      KBase.setRotationPoint(0F, 0F, 0F);
      KBase.setTextureSize(64, 32);
      KBase.mirror = true;
      setRotation(KBase, 0F, 0F, 0F);
      KNossel = new ModelRenderer(this, 30, 0);
      KNossel.addBox(-1F, 12F, -1F, 2, 2, 2);
      KNossel.setRotationPoint(0F, 0F, 0F);
      KNossel.setTextureSize(64, 32);
      KNossel.mirror = true;
      setRotation(KNossel, 0F, 0F, 0F);
      KPart = new ModelRenderer(this, 16, 0);
      KPart.addBox(-2F, 14F, -1.5F, 4, 1, 3);
      KPart.setRotationPoint(0F, 0F, 0F);
      KPart.setTextureSize(64, 32);
      KPart.mirror = true;
      setRotation(KPart, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    KBase.render(f5);
    KNossel.render(f5);
    KPart.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
